# Generated by Django 5.1.3 on 2025-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_teacher_assignment_delete_student_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_assignment',
            name='Roll',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
