# Generated by Django 5.1.3 on 2025-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_student_roll_teacher_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
