# Generated by Django 5.1.3 on 2025-06-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=200, unique=True)),
                ('No_of_Sections', models.IntegerField()),
            ],
        ),
    ]
