# Generated by Django 5.1.3 on 2025-06-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_assignment',
            name='Assignment_File',
        ),
    ]
