# Generated by Django 5.1.3 on 2025-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_assignment_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assignment',
            name='Roll_No',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
