# Generated by Django 5.1.3 on 2025-06-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_assignment_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_assignment',
            old_name='Roll_No',
            new_name='Roll',
        ),
    ]
