# Generated by Django 5.1.3 on 2025-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_rename_roll_no_student_assignment_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assignment',
            name='Grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student_assignment',
            name='Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
