# Generated by Django 5.1.3 on 2025-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_assignment_grade_student_assignment_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100, unique=True)),
                ('No_of_Sections', models.IntegerField()),
            ],
        ),
    ]
