# Generated by Django 5.1.3 on 2025-06-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_coursesectioninfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSectionInfo',
        ),
    ]
